baseURL = "https://gigitbra.my.id/"
languageCode = "en-us"
title = "BRA-RestoHugo"
theme = "Resto Hugo"
copyright = "&copy 2019 Resto Hugo" # HTML tags supported
googleAnalytics = "UA-123-45"
disqusShortname = "yourdiscussshortname"

# Theme specific configuration
[params]
logo = "img/logo.png"
enableDisqus = true # enable / disable comments for blog posts
enableGA = true # enable / disable google analytics
heroText = "SEWA MOBIL JOGJA <br> <hr> PENGINAPAN MURAH JOGJA<p>&#128512;</p>"
footerText = "Ini Demo Mode"
facebook = "https://facebook.com"
twitter = "https://twitter.com"
instagram = "https://instagram.com"

